apiVersion: apps/v1
kind: Deployment
metadata:
  name: olamundo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: olamundo
  template:
    metadata:
      labels:
        app: olamundo
    spec:
      containers:
      - name: olamundo
        image: luis01filipe/olamundo-flask:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: olamundo-service
spec:
  selector:
    app: olamundo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
